# Generated by Django 5.1.6 on 2025-03-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kebabs',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='kebabs',
            name='type',
        ),
        migrations.AddField(
            model_name='kebabs',
            name='ingredients',
            field=models.ManyToManyField(to='kebab_order.ingredients'),
        ),
        migrations.AddField(
            model_name='kebabs',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kebab', to='kebab_order.type'),
        ),
    ]
