# Generated by Django 5.1.7 on 2025-03-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0003_remove_ingredients_id_remove_ingredients_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
