# Generated by Django 5.1.7 on 2025-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0004_ingredients_id_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebabs',
            name='type',
            field=models.CharField(choices=[('B', 'Beef'), ('C', 'Chicken')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
