# Generated by Django 5.1.7 on 2025-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0005_alter_kebabs_type_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebabs',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kebabs',
            name='price',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='kebabs',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
