# Generated by Django 5.1.7 on 2025-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0007_order_remove_kebabs_address_alter_kebabs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kebabs',
            field=models.ManyToManyField(to='kebab_order.kebabs'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
