# Generated by Django 5.1.7 on 2025-03-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_order', '0009_order_user_alter_kebabs_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
